spring:
  application:
    name: postgres-keycloak
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



server:
  port: ${PORT:8081}


keycloak:
  server-url: http://localhost:8080
  realm: myrealm
  client-id: admin-cli
  username: admin
  password: admin


